# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8KMcFFbaH_IbjkUo4djHTuQMDVlJE_L
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_predict

try:
    df = pd.read_csv('results.csv')
except FileNotFoundError:
    df = pd.read_csv('/results.csv')

df = df.dropna(subset=['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']).copy()

df['TotalGoals'] = df['FTHG'] + df['FTAG']

X = pd.get_dummies(df[['HomeTeam', 'AwayTeam']], drop_first=True)
y = df['TotalGoals']

k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
model = LinearRegression()

df['y_pred'] = cross_val_predict(model, X, y, cv=kf)
df['Residual'] = df['TotalGoals'] - df['y_pred']

sns.set_theme(style='whitegrid')
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

sns.scatterplot(ax=axes[0], x=df['y_pred'], y=df['Residual'], alpha=0.3, color='#1f77b4', edgecolor=None)
axes[0].axhline(0, color='red', linestyle='--', linewidth=2, label='Residual = 0')
axes[0].set_title('Residuals vs. Predicted Values', fontsize=13, fontweight='bold')
axes[0].set_xlabel(r'Predicted Total Goals ($\hat{y}$)', fontsize=11)
axes[0].set_ylabel(r'Residual ($y - \hat{y}$)', fontsize=11)
axes[0].legend()

sns.histplot(ax=axes[1], x=df['Residual'], kde=True, color='#2ca02c', bins=30)
axes[1].axvline(0, color='red', linestyle='--', linewidth=2, label='Zero Error')
axes[1].set_title('Distribution of Residuals', fontsize=13, fontweight='bold')
axes[1].set_xlabel(r'Residual ($y - \hat{y}$)', fontsize=11)
axes[1].set_ylabel('Frequency', fontsize=11)
axes[1].legend()

plt.tight_layout()
plt.show()

big_six = ['Man United', 'Arsenal', 'Chelsea', 'Liverpool', 'Man City', 'Tottenham']

def assign_sector(row):
    home_big = row['HomeTeam'] in big_six
    away_big = row['AwayTeam'] in big_six
    if home_big and away_big:
        return 'Top 6 Clash'
    elif home_big or away_big:
        return 'Top 6 vs Mid/Lower'
    else:
        return 'Mid/Lower Table'

df['Sector'] = df.apply(assign_sector, axis=1)

sector_summary = df.groupby('Sector')['Residual'].agg(
    MAE=lambda r: np.mean(np.abs(r)),
    RMSE=lambda r: np.sqrt(np.mean(r**2)),
    Mean_Residual='mean',
    Count='count'
).reset_index()

print("--- Sector Performance Breakdown ---")
display(sector_summary)

"""Choice of $k$ (Cross-Validation Justification)We set $k=5$ folds. Given our dataset size of over 11,000 matches, each training fold contains ~8,890 observations (80%), which prevents model parameter estimation bias.$k=5$ offers an optimal computational trade-off over $k=10$ or leave-one-out validation by maintaining low fold variance without redundant training iterations.

1. Are the residuals centered around zero?

  Yes. The mean residual is mathematically $\approx 0$ ($\mu \approx -8.4 \times 10^{-5}$), which is consistent with the optimization guarantees of Ordinary Least Squares (OLS).The residual distribution is slightly right-skewed ($\text{Median} \approx -0.175$) because actual goals are bounded non-negative integers ($y \ge 0$), whereas linear regression assumes a symmetric Gaussian noise profile.
\

Do the residuals exhibit any systematic patterns?                       

    Yes. The scatter plot shows discrete, parallel diagonal bands.This pattern occurs when fitting a continuous linear model to discrete count data ($y \in \{0, 1, 2, \dots\}$). For each actual outcome $y = c$, the residual follows the linear line $\text{Residual} = c - \hat{y}$.

Is there evidence of heteroscedasticity?

 Yes. The residual dispersion is non-constant across predicted values:For lower predictions ($\hat{y} < 2.5$), residuals cluster tightly around zero.For higher predictions ($\hat{y} > 3.0$), the spread expands into a noticeable funnel shape, showing that higher-scoring matches carry higher stochastic variance.

Is there a sector that is more likely to have high error rates? If so, why do you think this is happening?

 Yes. As quantified in the breakdown table, matches involving elite teams show higher error rates:Top 6 Clash: $\text{RMSE} \approx 1.74$, $\text{MAE} \approx 1.36$Top 6 vs Mid/Lower: $\text{RMSE} \approx 1.73$, $\text{MAE} \approx 1.38$Mid/Lower Table: $\text{RMSE} \approx 1.63$, $\text{MAE} \approx 1.31$Underlying Reasons:Tactical Variability: High-stakes matches between top clubs produce extreme outcomes depending on match strategy (defensive low-blocks yielding 0–0 vs. open high-press games yielding 4–3), which static linear baselines cannot capture.Blowouts & Asymmetry: Matches pitting elite offenses against lower-tier clubs periodically produce high-margin blowouts (5–0, 6–1), creating large positive residual outliers.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_predict

try:
    df = pd.read_csv('results.csv')
except FileNotFoundError:
    df = pd.read_csv('/results.csv')

df = df.dropna(subset=['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']).copy()
df['TotalGoals'] = df['FTHG'] + df['FTAG']

home_stats = df.groupby('HomeTeam').agg(
    Home_Avg_Scored=('FTHG', 'mean'),
    Home_Avg_Conceded=('FTAG', 'mean')
).reset_index()

away_stats = df.groupby('AwayTeam').agg(
    Away_Avg_Scored=('FTAG', 'mean'),
    Away_Avg_Conceded=('FTHG', 'mean')
).reset_index()

df = df.merge(home_stats, on='HomeTeam', how='left')
df = df.merge(away_stats, on='AwayTeam', how='left')

features = ['Home_Avg_Scored', 'Home_Avg_Conceded', 'Away_Avg_Scored', 'Away_Avg_Conceded']
X = df[features]
y = df['TotalGoals']

kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = LinearRegression()

df['y_pred'] = cross_val_predict(model, X, y, cv=kf)
df['Residual'] = df['TotalGoals'] - df['y_pred']
df['Absolute_Error'] = np.abs(df['Residual'])

sns.set_theme(style='whitegrid')
fig, axes = plt.subplots(len(features), 2, figsize=(16, 4 * len(features)))

for i, col in enumerate(features):
    sns.scatterplot(ax=axes[i, 0], x=df[col], y=df['Residual'], alpha=0.25, color='#1f77b4', edgecolor=None)
    sns.regplot(ax=axes[i, 0], x=df[col], y=df['Residual'], scatter=False, color='red', lowess=True)
    axes[i, 0].axhline(0, color='black', linestyle='--', linewidth=1.2)
    axes[i, 0].set_title(f'{col} vs. Residuals', fontsize=12, fontweight='bold')
    axes[i, 0].set_xlabel(col, fontsize=10)
    axes[i, 0].set_ylabel(r'Residual ($y - \hat{y}$)', fontsize=10)

    sns.scatterplot(ax=axes[i, 1], x=df[col], y=df['Absolute_Error'], alpha=0.25, color='#ff7f0e', edgecolor=None)
    sns.regplot(ax=axes[i, 1], x=df[col], y=df['Absolute_Error'], scatter=False, color='darkred', lowess=True)
    axes[i, 1].set_title(f'{col} vs. Absolute Errors', fontsize=12, fontweight='bold')
    axes[i, 1].set_xlabel(col, fontsize=10)
    axes[i, 1].set_ylabel(r'Absolute Error ($|y - \hat{y}|Short$)', fontsize=10)

plt.tight_layout()
plt.show()

"""Finding: The LOWESS trend lines across all feature vs. residual plots remain flat at zero without parabolic or polynomial curvature.

Interpretation: There is no strong single-feature polynomial trend overlooked by the linear model; however, the discrete banding indicates that linear combination fails to capture interaction effects (e.g., strong attack vs. weak defense synergy).

Feature-Dependent Error PatternsFinding: Plotting Home_Avg_Scored against Absolute_Error demonstrates an upward drift at higher feature values ($> 1.8$ goals/game).Interpretation: When home teams have historically dominant attacks, prediction errors increase. High-scoring attacks introduce higher variance per match due to game-state dynamics (blowouts vs. defensive adaptations).

Hidden Subpopulations

Finding: Discrete horizontal clusters appear at the extreme ends of the feature spectrum (e.g., clubs with very high historical scoring averages, such as Manchester City or Arsenal, compared to newly promoted clubs with lower historical sample sizes).

Interpretation: Elite teams form a distinct subpopulation that exhibits wider error distribution compared to standard mid-table matchups, confirming the necessity of hierarchical modeling or interaction features.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df['Absolute_Error'] = np.abs(df['Residual'])

threshold_95 = np.percentile(df['Absolute_Error'], 95)
top_5_percent = df[df['Absolute_Error'] >= threshold_95].sort_values(by='Absolute_Error', ascending=False)

print(f"95th Percentile Absolute Error Threshold: {threshold_95:.2f}")
print(f"Total Extreme Outlier Observations (Top 5%): {len(top_5_percent)}\n")

top_cols = ['Season', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'TotalGoals', 'y_pred', 'Residual', 'Absolute_Error']
print("--- Top 10 Extreme Error Matches ---")
display(top_5_percent[top_cols].head(10))

plt.figure(figsize=(10, 4))
sns.countplot(data=top_5_percent, x='TotalGoals', palette='Reds_r')
plt.title('Distribution of Actual Total Goals in Top 5% Extreme Errors', fontsize=12, fontweight='bold')
plt.xlabel('Actual Total Goals ($y$)', fontsize=10)
plt.ylabel('Count of Extreme Matches', fontsize=10)
plt.show()

"""dentification of Extreme Errors (Top 5%)The 95th percentile error threshold is 3.15 goals.Any match where $\vert{}y - \hat{y}\vert{} \ge 3.15$ (556 observations) is classified as an extreme error outlier.The most severe errors include historical anomalies such as Portsmouth vs. Reading (7–4, error of +8.33), Tottenham vs. Wigan (9–1, error of +7.28), and Manchester United vs. Arsenal (8–2, error of +7.14).

Discussion on the Sources of Extreme Errors

Data Quality Issues:

Evaluation: Not the primary cause.

The extreme scores recorded in the dataset correspond to verified historical Premier League matches (e.g., Aston Villa 7–2 Liverpool in 2020, West Brom 5–5 Man United in 2013). There is no evidence of corrupted recordings, misaligned schema columns, or typos.

Model Limitations:

Evaluation: Significant contributor.

Linear & Additive Restriction: The linear regression baseline relies purely on static team dummy coefficients, assuming independent, additive effects. It cannot model dynamic situational variables such as red cards, early goals forcing tactical collapses, key player injuries, or defensive collapse under extreme pressure.

Conditional Mean Regression: Linear regression optimizes for the expected conditional mean $E[Y\vert{}X] \approx 2.5 - 3.2$ goals. It systematically under-predicts heavy-tailed distributions and lacks non-linear interaction terms (e.g., high-line pressing against rapid counter-attacking teams).

Rare or Exceptional Cases (Stochastic Volatility):Evaluation: Primary root cause.Over 97% of extreme error observations occur when actual match goals exceed 6 ($y \in [6, 11]$). In professional football, single-match scorelines with 7 to 11 goals are rare, black-swan statistical anomalies governed by high stochastic randomness. Because these events occur far out in the distribution's tail, they represent natural domain aleatoric uncertainty rather than systematic data corruption.
"""

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

mae = np.mean(np.abs(df['Residual']))
std_residuals = np.std(df['Residual'], ddof=1)
skewness_val = stats.skew(df['Residual'])
kurtosis_fisher = stats.kurtosis(df['Residual'], fisher=True)   # Normal = 0
kurtosis_pearson = stats.kurtosis(df['Residual'], fisher=False) # Normal = 3

metrics_table = pd.DataFrame({
    'Metric': [
        'Mean Absolute Error (MAE)',
        'Standard Deviation of Residuals ($\sigma$)',
        'Skewness',
        'Excess Kurtosis (Fisher)',
        'Kurtosis (Pearson)'
    ],
    'Value': [
        f"{mae:.4f}",
        f"{std_residuals:.4f}",
        f"{skewness_val:.4f}",
        f"{kurtosis_fisher:.4f}",
        f"{kurtosis_pearson:.4f}"
    ],
    'Reference (Standard Normal)': [
        '--',
        '--',
        '0.0',
        '0.0',
        '3.0'
    ]
})

print("--- Statistical Properties of Residuals ---")
display(metrics_table)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(df['Residual'], kde=True, stat="density", color="teal", bins=30, ax=axes[0], label='Residuals Density')
x_range = np.linspace(df['Residual'].min(), df['Residual'].max(), 100)
axes[0].plot(x_range, stats.norm.pdf(x_range, 0, std_residuals), 'r--', lw=2, label='Theoretical Normal')
axes[0].set_title('Residuals vs. Normal Distribution', fontsize=12, fontweight='bold')
axes[0].set_xlabel(r'Residual ($y - \hat{y}$)', fontsize=10)
axes[0].legend()

stats.probplot(df['Residual'], dist="norm", plot=axes[1])
axes[1].set_title('Normal Q-Q Plot', fontsize=12, fontweight='bold')
axes[1].get_lines()[0].set_color('royalblue')
axes[1].get_lines()[0].set_alpha(0.4)
axes[1].get_lines()[1].set_color('red')

plt.tight_layout()
plt.show()

"""Quantitative Statistical SummaryMean Absolute Error (MAE): $\approx 1.34$ goals per match.Standard Deviation ($\sigma$): $\approx 1.68$ goals, reflecting the dispersion of error around the expected conditional mean.Skewness: $+0.596$ (Positive Skewness).Excess Kurtosis (Fisher): $+0.382$ (Pearson Kurtosis $= 3.382$, Leptokurtic).

Interpretation & DiscussionSkewness & Systematic Bias:Observation: The skewness is strictly positive ($\gamma_1 = +0.596$).Interpretation: Positive skewness indicates an asymmetric tail extending toward large positive residuals ($y \gg \hat{y}$). Because actual total goals are bounded from below by zero ($y \ge 0$) but unbounded from above, the model systematically under-predicts high-scoring fixtures while concentrating errors in a narrower negative band ($y < \hat{y}$).

Kurtosis & Model Instability (Heavy Tails):Observation: The distribution is leptokurtic with positive excess kurtosis ($\text{Kurtosis} > 3$).Interpretation: The residuals exhibit heavier tails compared to a standard Gaussian distribution. As shown in the Q-Q plot, the extreme quantiles deviate upwards from the theoretical line. This confirms model sensitivity and instability when encountering rare high-scoring matches ($7+$ goals), demonstrating that the normal noise assumption of linear regression does not fully hold for count-based event modeling.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

try:
    df = pd.read_csv('results.csv')
except FileNotFoundError:
    df = pd.read_csv('/results.csv')

df = df.dropna(subset=['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']).copy()
df['TotalGoals'] = df['FTHG'] + df['FTAG']

home_stats = df.groupby('HomeTeam').agg(
    Home_Avg_Scored=('FTHG', 'mean'),
    Home_Avg_Conceded=('FTAG', 'mean')
).reset_index()

away_stats = df.groupby('AwayTeam').agg(
    Away_Avg_Scored=('FTAG', 'mean'),
    Away_Avg_Conceded=('FTHG', 'mean')
).reset_index()

df = df.merge(home_stats, on='HomeTeam', how='left')
df = df.merge(away_stats, on='AwayTeam', how='left')

features = ['Home_Avg_Scored', 'Home_Avg_Conceded', 'Away_Avg_Scored', 'Away_Avg_Conceded']
X = df[features]
y = df['TotalGoals']

kf = KFold(n_splits=5, shuffle=True, random_state=42)

models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(max_depth=5, min_samples_split=20, random_state=42),
    'Random Forest': RandomForestRegressor(n_estimators=100, max_depth=6, min_samples_split=20, random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=100, max_depth=3, learning_rate=0.05, random_state=42),
    'KNN Regressor (Bonus)': KNeighborsRegressor(n_neighbors=25)
}

results = []
predictions = {}

for name, model in models.items():
    preds = cross_val_predict(model, X, y, cv=kf)
    predictions[name] = preds
    mse = mean_squared_error(y, preds)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y, preds)
    r2 = r2_score(y, preds)
    residuals = y - preds
    std_res = np.std(residuals, ddof=1)

    results.append({
        'Model Architecture': name,
        'MSE': mse,
        'RMSE': rmse,
        'MAE': mae,
        'R^2 Score': r2,
        'Residual Std': std_res
    })

comparison_df = pd.DataFrame(results)
print("--- Model Performance Comparison Table ---")
display(comparison_df.round(4))

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

metrics_bar = comparison_df.set_index('Model Architecture')[['MAE', 'RMSE']]
metrics_bar.plot(kind='bar', ax=axes[0], colormap='viridis', rot=25)
axes[0].set_title('Model Error Metrics (MAE vs. RMSE)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Error (Goals)', fontsize=10)
axes[0].grid(True, linestyle=':', alpha=0.6)

for name, preds in predictions.items():
    sns.kdeplot(y - preds, label=name, ax=axes[1], lw=1.8)
axes[1].axvline(0, color='red', linestyle='--', linewidth=1.5)
axes[1].set_title('Residual Density Curves Across Architectures', fontsize=12, fontweight='bold')
axes[1].set_xlabel(r'Residual ($y - \hat{y}$)', fontsize=10)
axes[1].legend()

plt.tight_layout()
plt.show()

"""Analysis: Linear Regression slightly outperforms all non-linear and ensemble alternatives across all quantitative criteria ($\text{RMSE} = 1.6647, R^2 = 0.0177$). The near-zero $R^2$ values across every family reflect the fundamentally high aleatoric noise in single-match football goal events.

Fulfillment of Model AssumptionsLinearity: Satisfied on an aggregated level (higher historical team scoring rates linearly correlate with higher expected game goals), though individual matches deviate substantially.Independence of Observations: Violated longitudinally due to temporal correlation between consecutive games of a team across seasons (form, managerial shifts, transfer windows).Homoscedasticity: Partially violated; variance increases slightly for high-scoring expectations ($\hat{y} > 3.0$).

Differences in the Bias–Variance Trade-off

Linear Regression: High bias / very low variance. Its rigid functional form prevents overfitting to idiosyncratic fixture outcomes.

Decision Tree: Low bias / high variance. Single trees over-partition the feature space and fit random noise in small sample leaves.

Ensembles (Random Forest / Gradient Boosting): Successfully reduce variance (RF via bagging) and bias (GB via sequential boosting), establishing a robust balance, though bounded by the low signal-to-noise ratio of the domain.

Sensitivity of the Models to Outliers and NoiseLinear Regression & Decision Trees: Highly sensitive to outlier scores ($7-2, 8-2, 9-1$) due to the quadratic penalization in MSE loss, which shifts OLS hyperplanes and triggers deep tree splits.Random Forest & Gradient Boosting: Display higher robustness against noise by aggregating multiple weak learners and subsampling training instances.

Failure Scenarios for Linear Models

Failure Modes: Linear models fail during extreme tactical shifts (e.g., severe defensive low-blocks, red cards, late-game blowouts where trailing teams concede repeatedly on counter-attacks).

Cause: Inability to model non-monotonic threshold effects and complex multi-variable interactions without manual polynomial expansion.

Situations Where Tree-Based Models Provide Advantages

Effective when distinct non-linear regimes exist in the feature space (e.g., specific interactions where high-scoring home teams against low-scoring away teams produce non-linear blowout probabilities).

Handle categorical groupings and non-standard feature distributions without requiring strict feature scaling or normalization.

Trade-off Between Interpretability and Predictive Performance

Linear Regression: Highly interpretable; coefficients directly quantify the marginal goal contribution per unit change in offensive/defensive averages.

Ensemble Models: Act as black-box models with negligible empirical accuracy gains in this specific low-signal dataset, making the simpler linear formulation preferable.

Preferred Model Selection & JustificationSelection: Linear Regression (or regularized Ridge/Poisson Regression as a specialized variant).Justification: Following Occam’s Razor, Linear Regression achieves the lowest RMSE ($1.6647$), zero excess computational overhead, and clear interpretability, outperforming complex ensembles on this dataset.

Key Learnings from the Modeling StageMatch-level goal totals in football are dominated by stochastic randomness (aleatoric uncertainty), placing an empirical upper bound on regression $R^2$ scores regardless of model complexity.Model selection must align with data properties: increasing model complexity on noisy, low-feature datasets often induces overfitting rather than predictive gain.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report

try:
    df = pd.read_csv('results.csv')
except FileNotFoundError:
    df = pd.read_csv('/results.csv')

df = df.dropna(subset=['HomeTeam', 'AwayTeam', 'FTR']).copy()

df['HomeWin'] = (df['FTR'] == 'H').astype(int)

home_wr = df.groupby('HomeTeam')['HomeWin'].mean().reset_index().rename(columns={'HomeWin': 'HomeTeam_HomeWinRate'})
away_lr = df.groupby('AwayTeam')['HomeWin'].mean().reset_index().rename(columns={'HomeWin': 'AwayTeam_AwayLossRate'})

df = df.merge(home_wr, on='HomeTeam', how='left')
df = df.merge(away_lr, on='AwayTeam', how='left')

features = ['HomeTeam_HomeWinRate', 'AwayTeam_AwayLossRate']
X = df[features]
y = df['HomeWin']

kf = KFold(n_splits=5, shuffle=True, random_state=42)
clf = LogisticRegression(random_state=42)

df['y_pred_cls'] = cross_val_predict(clf, X, y, cv=kf)

cm = confusion_matrix(y, df['y_pred_cls'])
tn, fp, fn, tp = cm.ravel()

plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted: Not Home Win (0)', 'Predicted: Home Win (1)'],
            yticklabels=['Actual: Not Home Win (0)', 'Actual: Home Win (1)'])
plt.title('Confusion Matrix - Binary Home Win Classification', fontsize=13, fontweight='bold')
plt.ylabel('Actual Label', fontsize=11)
plt.xlabel('Predicted Label', fontsize=11)
plt.tight_layout()
plt.show()

print("--- Classification Report ---")
print(classification_report(y, df['y_pred_cls'], target_names=['Not Home Win (0)', 'Home Win (1)']))

"""Confusion Matrix Breakdown & Rate Interpretation

True Negatives (TN = 4,422): Matches where the home team did not win (Draw/Away win) and the model correctly predicted so.

True Positives (TP = 2,626): Matches where the home team won and the model correctly predicted a home victory.

False Positives (FP = 1,603 / Type I Error): The model predicted a home win, but the match ended in a draw or away win.

False Negatives (FN = 2,462 / Type II Error): The home team won, but the model predicted they would not win.

Which Type of Error is Most Critical in This Context?

In domain applications such as sports betting analytics, financial risk deployment, or tactical allocation, False Positives (Type I Error) are generally more critical. Predicting a high-confidence home win when the event fails incurs direct financial drawdown or tactical miscalculation.From a pure statistical modeling perspective, False Negatives (Type II Error) are prevalent here ($\text{FN} = 2,462$ vs $\text{Recall} = 0.52$), reflecting the model’s conservatism in identifying winning outcomes for mid-tier teams.:

Balanced/Contested Fixtures:

The model struggles significantly when two evenly-matched teams compete (e.g., mid-table clashes where predicted probabilities hover between $45\% - 55\%$).

 In these regions, high domain stochasticity causes predictions to oscillate across the classification boundary.Draw Erasure (in Multiclass):

 When evaluating multi-class formulations ($H, D, A$), standard discriminative models fail systematically on Draws ($D$), outputting zero draw predictions because draws rarely have the highest argmax posterior probability despite comprising ~25% of all fixtures.

Class Imbalance & Home Bias: While home wins represent the single largest plurality outcome (~45.8%), they do not form an absolute majority. Simple linear classifiers tilt toward the majority class baseline and produce high Type II error rates.Predictability Ceiling: Match outcome classification based purely on historical win/loss ratios reaches a natural accuracy boundary ($\approx 63\%$). Achieving higher separation requires granular in-game state dynamics (expected goals/xG, player availability, pressing intensity) to resolve unmodeled variance.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_predict

proba = cross_val_predict(clf, X, y, cv=kf, method='predict_proba')
df['p_home_win'] = proba[:, 1]
df['y_pred_cls'] = (df['p_home_win'] >= 0.5).astype(int)

df['confidence'] = np.where(df['y_pred_cls'] == 1, df['p_home_win'], 1 - df['p_home_win'])
df['is_correct'] = (df['y_pred_cls'] == df['HomeWin']).astype(int)
df['prediction_status'] = np.where(df['is_correct'] == 1, 'Correct', 'Incorrect')

sns.set_theme(style='whitegrid')
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

sns.histplot(ax=axes[0], data=df, x='confidence', hue='prediction_status',
             bins=30, kde=True, palette={'Correct': '#2ca02c', 'Incorrect': '#d62728'}, alpha=0.5)
axes[0].set_title('Confidence Distribution: Correct vs. Incorrect Predictions', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Model Confidence (Probability of Predicted Class)', fontsize=10)
axes[0].set_ylabel('Match Count', fontsize=10)

sns.boxplot(ax=axes[1], data=df, x='prediction_status', y='confidence', palette={'Correct': '#2ca02c', 'Incorrect': '#d62728'})
axes[1].set_title('Confidence Spread by Classification Outcome', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Prediction Outcome', fontsize=10)
axes[1].set_ylabel('Model Confidence', fontsize=10)

plt.tight_layout()
plt.show()

high_conf_errors = df[(df['is_correct'] == 0) & (df['confidence'] >= 0.70)].sort_values(by='confidence', ascending=False)
print(f"Total High-Confidence Errors (Confidence >= 70%): {len(high_conf_errors)}\n")

cols_to_show = ['Season', 'HomeTeam', 'AwayTeam', 'FTR', 'HomeWin', 'y_pred_cls', 'confidence']
print("--- Top 10 High-Confidence Errors (Major Upsets) ---")
display(high_conf_errors[cols_to_show].head(10))

"""Comparison of Predicted Probabilities (Correct vs. Incorrect)

 Correct Predictions: Display an average confidence of 64.7%, with probability distributions peaking higher toward confident regions ($> 0.70$).

 Incorrect Predictions: Display a lower average confidence of 61.1%, concentrated primarily in ambiguous decision boundary zones ($0.50 - 0.65$).

 Statistical Implication: The model exhibits moderate calibration; its confidence decreases when evaluating uncertain, evenly contested fixtures.

Identification & Analysis of High-Confidence Errors

 Quantitative Threshold: Filtering for false predictions made with $\ge 70\%$ confidence isolates 609 extreme classification failures.

 Major Historical Upsets Identified:

 Huddersfield vs. Manchester United (2017–18): Model predicted an 89.1% probability of Man United avoiding defeat ($\hat{y} = 0$), but Huddersfield secured a 2–1 home win ($y = 1$).

 Liverpool vs. Barnsley (1997–98): Model assigned an 87.3% probability to a Liverpool home win ($\hat{y} = 1$), but Barnsley won 0–1 away ($y = 0$).

 Watford vs. Manchester United (2019–20): Model assigned an 86.0% confidence against a home victory, but Watford won 2–0.

Root Causes of High-Confidence Failures

Over-Reliance on Historical Priors: The logistic regression model uses historical win/loss base rates, causing it to assign extreme probabilities against newly promoted or lower-table teams playing historical giants.

Failure to Capture Match Realities: High-confidence failures represent classic sporting "upsets" driven by unmodeled dynamic factors (e.g., fatigue, red cards, squad rotation, motivation shifts) that override baseline club strength.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_predict

df['Strength_Difference'] = df['HomeTeam_HomeWinRate'] - df['AwayTeam_AwayLossRate']

features_to_plot = ['HomeTeam_HomeWinRate', 'AwayTeam_AwayLossRate', 'Strength_Difference']

sns.set_theme(style='whitegrid')
fig, axes = plt.subplots(len(features_to_plot), 2, figsize=(15, 4 * len(features_to_plot)))

palette_colors = {'Correct': '#2ca02c', 'Incorrect': '#d62728'}

for i, col in enumerate(features_to_plot):
    sns.kdeplot(ax=axes[i, 0], data=df, x=col, hue='prediction_status',
                palette=palette_colors, common_norm=False, fill=True, alpha=0.3, lw=2)
    axes[i, 0].set_title(f'Density Distribution of {col}', fontsize=12, fontweight='bold')
    axes[i, 0].set_xlabel(col, fontsize=10)
    axes[i, 0].set_ylabel('Density', fontsize=10)

    sns.boxplot(ax=axes[i, 1], data=df, x='prediction_status', y=col,
                palette=palette_colors, width=0.4)
    axes[i, 1].set_title(f'Spread of {col} by Prediction Accuracy', fontsize=12, fontweight='bold')
    axes[i, 1].set_xlabel('Prediction Status', fontsize=10)
    axes[i, 1].set_ylabel(col, fontsize=10)

plt.tight_layout()
plt.show()

feature_summary = df.groupby('prediction_status')[features_to_plot].agg(['mean', 'std', 'median']).T
print("--- Feature Statistics by Prediction Accuracy ---")
display(feature_summary.round(4))

""" Identification of Regions Prone to Misclassification

 The "Parity Zone" ($\text{Strength\_Difference} \approx 0$):

 The density curves demonstrate that incorrect predictions are concentrated heavily in the central range where HomeTeam_HomeWinRate and AwayTeam_AwayLossRate are nearly identical.

 When two teams have comparable strength metrics, the match outcome is dominated by in-game variance (match-level luck, referee decisions, defensive lapses), leading to a high misclassification rate.

  Subpopulation Degradation & Asymmetry
  
  Mid-Table Subpopulation: The model performs reliably at the extremes (elite teams playing at home against bottom-table sides, or vice versa), but degrades significantly across the large subpopulation of mid-table fixtures ($0.35 - 0.50$ win rates).
  
  High Away-Resilience: Away teams with low loss rates (strong defensive records on the road) frequently trigger false positive home wins, as the simple model over-weights average home advantage.
  
   Actionable Insights for Future Modeling
   
   Need for Non-Linear Interactions: Linear feature representations fail to capture stylistic matchups (e.g., counter-attacking styles vs. possession-based teams).
   
   Dynamic Time-Decayed Form: Replacing aggregate historical averages with rolling window metrics (last 5–10 games) and advanced metrics (Expected Goals - xG) is critical to capturing current team trajectory and breaking through the mid-table ambiguity region.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.metrics import (precision_score, recall_score, f1_score,
                             fbeta_score, matthews_corrcoef, roc_curve, roc_auc_score)

try:
    df = pd.read_csv('results.csv')
except FileNotFoundError:
    df = pd.read_csv('/results.csv')

df = df.dropna(subset=['HomeTeam', 'AwayTeam', 'FTR']).copy()
df['HomeWin'] = (df['FTR'] == 'H').astype(int)

home_wr = df.groupby('HomeTeam')['HomeWin'].mean().reset_index().rename(columns={'HomeWin': 'HomeTeam_HomeWinRate'})
away_lr = df.groupby('AwayTeam')['HomeWin'].mean().reset_index().rename(columns={'HomeWin': 'AwayTeam_AwayLossRate'})

df = df.merge(home_wr, on='HomeTeam', how='left')
df = df.merge(away_lr, on='AwayTeam', how='left')

features = ['HomeTeam_HomeWinRate', 'AwayTeam_AwayLossRate']
X = df[features]
y = df['HomeWin']

kf = KFold(n_splits=5, shuffle=True, random_state=42)
clf = LogisticRegression(random_state=42)
y_proba = cross_val_predict(clf, X, y, cv=kf, method='predict_proba')[:, 1]

thresholds = np.arange(0.1, 1.0, 0.1)
threshold_metrics = []

for t in thresholds:
    y_pred_t = (y_proba >= t).astype(int)
    threshold_metrics.append({
        'Threshold': round(t, 1),
        'Precision': precision_score(y, y_pred_t, zero_division=0),
        'Recall': recall_score(y, y_pred_t, zero_division=0),
        'F1-Score': f1_score(y, y_pred_t, zero_division=0),
        'MCC': matthews_corrcoef(y, y_pred_t)
    })

thresh_df = pd.DataFrame(threshold_metrics)
print("--- Threshold Sensitivity Performance Table ---")
display(thresh_df.round(4))

sns.set_theme(style='whitegrid')
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(thresh_df['Threshold'], thresh_df['Precision'], marker='o', label='Precision', lw=2)
axes[0].plot(thresh_df['Threshold'], thresh_df['Recall'], marker='s', label='Recall', lw=2)
axes[0].plot(thresh_df['Threshold'], thresh_df['F1-Score'], marker='^', label='F1-Score', lw=2)
axes[0].plot(thresh_df['Threshold'], thresh_df['MCC'], marker='d', label='MCC', lw=2)
axes[0].set_title('Metrics vs. Decision Threshold', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Decision Threshold', fontsize=10)
axes[0].set_ylabel('Score', fontsize=10)
axes[0].legend()

betas = np.linspace(0.1, 3.0, 50)
for t_val in [0.3, 0.4, 0.5, 0.6, 0.7]:
    preds = (y_proba >= t_val).astype(int)
    f_betas = [fbeta_score(y, preds, beta=b, zero_division=0) for b in betas]
    axes[1].plot(betas, f_betas, label=f'Threshold = {t_val}', lw=2)
axes[1].set_title(r'$F_\beta$-Score vs. $\beta$', fontsize=12, fontweight='bold')
axes[1].set_xlabel(r'$\beta$ (Recall Weight)', fontsize=10)
axes[1].set_ylabel(r'$F_\beta$ Score', fontsize=10)
axes[1].legend()

fpr, tpr, _ = roc_curve(y, y_proba)
auc_score = roc_auc_score(y, y_proba)
axes[2].plot(fpr, tpr, color='darkorange', lw=2.5, label=f'ROC Curve (AUC = {auc_score:.3f})')
axes[2].plot([0, 1], [0, 1], color='navy', lw=1.5, linestyle='--', label='Random Guess')
axes[2].set_title('Receiver Operating Characteristic (ROC)', fontsize=12, fontweight='bold')
axes[2].set_xlabel('False Positive Rate (FPR)', fontsize=10)
axes[2].set_ylabel('True Positive Rate (TPR)', fontsize=10)
axes[2].legend(loc='lower right')

plt.tight_layout()
plt.show()



"""AUC–ROC Performance: The model achieves an $\text{AUC} \approx 0.68$, indicating moderate discriminative power superior to random guessing ($\text{AUC} = 0.50$).

 Analysis: Trade-off Between False Positives and False Negatives

 Low Thresholds ($t < 0.4$): The classifier aggressively predicts home wins ($\text{Recall} > 0.80$). This drastically minimizes False Negatives (missing genuine home victories) but floods the output with False Positives ($\text{Precision} \approx 0.50$), misclassifying draws and away wins as home wins.

 High Thresholds ($t > 0.6$): The classifier becomes highly selective ($\text{Precision} > 0.70$). This eliminates False Positives, ensuring that flagged games are high-probability home wins, but causes False Negatives to surge ($\text{Recall} < 0.30$).

  Identification of Stable vs. Unstable Operating Regions
  
  Stable Operating Region ($0.40 \le t \le 0.55$):
  
  The Matthews Correlation Coefficient (MCC) peaks in this interval ($\text{MCC} \approx 0.26$)
  
  .The classifier maintains balanced discriminative power across both classes without collapsing toward degenerate majority-class voting.
  
  Unstable / Degenerate Regions ($t < 0.2$ or $t > 0.8$):
  
  At $t \le 0.2$, the model degenerates by assigning positive predictions indiscriminately, causing MCC to drop toward zero.
  
  At $t \ge 0.8$, the decision boundary becomes overly strict, leading to extreme sparsity where almost no matches meet the threshold, causing $F_1$-scores to collapse toward zero.

3.5
Model Strengths and Limitations

Linear & Logistic Regression:

Strengths: Simple to understand, fast to run, and hard to overfit on noisy data.

Limitations: Cannot capture complex tactics, player combinations, or sudden match changes.

Tree and Ensemble Models (Random Forest, Gradient Boosting):

Strengths: Good at finding non-linear patterns and interactions between features.

Limitations: They act like a "black box" and did not improve the results because football match outcomes have a lot of pure luck (random noise).

2. Main Failure Modes

High-Scoring Games (
6+
 Goals): The models always under-predicted extreme blowouts (like 7–2 or 8–2 scores).

Close Matches (Even Teams): When two teams had similar strength, the model made the most mistakes because the winner was decided by random in-game events.

Draws and Big Upsets: The multi-class model struggled to predict draws, and the binary model missed major surprise wins by underdogs.

3. Model Assumptions vs. Real Match Data

Goal Distribution: Linear regression assumes errors are normal (Gaussian) with constant variance. In reality, goals are whole positive numbers (
0,1,2…
) and high-scoring games have much higher variance.

Match Independence: The models assumed each game is completely independent, ignoring real-life factors like current team form, manager changes, and player fatigue.

4. Key Insights from the Project

High Randomness in Football: A single match has a lot of luck and randomness. Complex models cannot find signals that are simply not there, which is why simple linear models performed just as well as complex ones.

Threshold Tuning Matters: Using the default
0.5
 threshold is not always best. Adjusting the threshold (between
0.40
 and
0.55
) allows us to balance false alarms and missed wins based on our goals.

5. Recommendations for Future Work

Use Count Models: Switch to Poisson Regression, which is designed specifically for counting goals.

Recent Form & Advanced Stats: Instead of all-time averages, use recent form (last 5 games) and advanced metrics like Expected Goals (xG).

Add Context: Include real-world features like rest days, key player injuries, and yellow/red cards.

4.

1. Where does the model fail most?

High-Scoring Matches ($6+$ Goals): The regression models consistently under-predicted high-scoring fixtures and extreme blowouts (e.g., 7–2 or 8–2).

Evenly-Matched Teams ("Parity Zone"): The classification model had the highest error rate in games between teams of similar strength, where the outcome is decided by small in-game events.

Draws and Major Upsets: The model struggled to predict draws and completely missed rare surprise wins by bottom-table teams against top-tier clubs.

2. Are failures due to data, model, or formulation?

Data: The dataset only contains final scores and team names. It lacks real-time information like current injuries, red cards, rest days, and in-game tactics. Football also has high natural randomness (luck).

Model: Linear and tree-based models could not capture complex tactical interactions between teams.

Formulation: Using standard Linear Regression (which assumes smooth normal errors) is not ideal for predicting whole positive goal counts ($0, 1, 2\dots$).

3. What improvements would you propose?


Recent Form & Advanced Stats: Use rolling averages (last 5–10 games) and advanced metrics like Expected Goals (xG) instead of all-time historical averages.

Contextual Features: Add key situational features such as player absences, manager changes, and days of rest between games.



4. What insights did you gain in your analysis?

High Randomness in Football: Single-match football outcomes contain significant noise, setting a natural limit on prediction accuracy regardless of model complexity.

Simple Models are Competitive: Because the signal-to-noise ratio is low, complex ensemble models did not outperform simple linear baselines and were more prone to fitting noise.

Value of Error Analysis: Looking at residuals, extreme errors, and threshold sensitivity gives a much deeper understanding of model behavior than simple overall accuracy metrics.
"""